---
- name: Ensure pacserve is installed from the repo
  pacman:
    name: pacserve
    state: present

- name: Ensure pacserve service is started and enabled
  service:
    name: pacserve
    enabled: yes
  notify:
    - "Restart pacserve service"

- name: Ensure pacman is set up to use pacserve
  include_role:
    name: pacman-repo
  vars:
    pacman_repo_name: "{{pacserve_repo}}"
    pacman_repo_server: "{{pacserve_server}}"
    pacman_add_includes:
      - "{{ pacserve_executable }}"
